[package]
name = "day01"
version.workspace = true
edition.workspace = true

[[bin]]
name = "day01"
path = "day01.rs"

[dependencies]
aoc2024-common = { workspace = true }
itertools = { workspace = true }
